[workspace]
resolver = "2"
members = [
    "ffi",
    "idevice",
    "tools",
    "pair_gui",
]

# Use the local `idevice/` crate everywhere with the right features:
[patch.crates-io]
idevice = { path = "idevice" }
